{
 "title": "Kube-burner Report",
 "description": "Kube-burner",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "uuid",
    "label": "UUID",
    "query": "{\"find\": \"terms\", \"field\": \"uuid.keyword\"}"
   },
   {
    "name": "master",
    "label": "Master nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\", \"query\": \"metricName.keyword: nodeRoles AND labels.role.keyword: master AND uuid.keyword: $uuid\"}"
   },
   {
    "name": "worker",
    "label": "Worker nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\", \"query\": \"metricName.keyword: nodeRoles AND labels.role.keyword: worker AND uuid.keyword: $uuid\"}"
   },
   {
    "name": "infra",
    "label": "Infra nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\",  \"query\": \"metricName.keyword: nodeRoles AND labels.role.keyword: infra AND uuid.keyword: $uuid\"}"
   },
   { "name": "latencyPercentile", "label": "Latency percentile", "query": "P99, P95, P50" }
  ]
 },
 "panels": [
  {
   "title": "Node count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4404",
       "fake": true,
       "field": "labels.role.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "coun",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeRoles\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Namespaces",
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"namespaceCount\" AND labels.phase: \"Active\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Services",
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"serviceCount\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Deployments",
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"deploymentCount\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Secrets",
     "bucketAggs": [
      {
       "$$hashKey": "object:705",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:703",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"secretCount\"",
     "timeField": "timestamp"
    },
    {
     "alias": "ConfigMaps",
     "bucketAggs": [
      {
       "$$hashKey": "object:705",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:703",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"configmapCount\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "OpenShift version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"etcdVersion\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "versi",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"etcdVersion\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: jobSummary",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: jobSummary AND NOT jobConfig.name: garbage-collection",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: alert",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Cluster status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Masters CPU utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.instance.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "settings": { "script": "_value*100" }, "type": "sum" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: nodeCPU-Masters AND NOT labels.mode.keyword: idle AND NOT labels.mode.keyword: steal",
       "timeField": "timestamp"
      },
      {
       "alias": "Aggregated",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "settings": { "script": "_value*100" }, "type": "sum" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: nodeCPU-Masters AND NOT labels.mode.keyword: idle AND NOT labels.mode.keyword: steal",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Masters Memory utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "Utilization {{labels.instance.keyword}}",
       "bucketAggs": [
        {
         "field": "labels.instance.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: nodeMemoryUtilization-Masters",
       "timeField": "timestamp"
      },
      {
       "alias": "Total {{labels.instance.keyword}}",
       "bucketAggs": [
        {
         "field": "labels.instance.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: nodeMemoryTotal-Masters",
       "timeField": "timestamp"
      },
      {
       "alias": "Aggregated utilization",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "sum" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: nodeMemoryUtilization-Masters",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Node status summary",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:4404",
         "fake": true,
         "field": "labels.condition.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeStatus\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Pod status summary",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:4404",
         "fake": true,
         "field": "labels.phase.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"podStatusCount\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Kube-apiserver usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerCPU\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      },
      {
       "alias": "Rss {{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerMemory\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      },
      {
       "alias": "Rss {{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerMemory-Masters\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      },
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerCPU-Masters\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Average kube-apiserver usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "Avg CPU kube-apiserver",
       "bucketAggs": [
        {
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      },
      {
       "alias": "Avg Rss kube-apiserver",
       "bucketAggs": [
        {
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.container.keyword: kube-apiserver",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Active Kube-controller-manager usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerCPU\" AND labels.container.keyword: kube-controller-manager",
       "timeField": "timestamp"
      },
      {
       "alias": "Rss {{labels.namespace.keyword}}-{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerMemory\" AND labels.container.keyword: kube-controller-manager",
       "timeField": "timestamp"
      },
      {
       "alias": "{{labels.namespace.keyword}}-{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerCPU-Masters\" AND labels.container.keyword: kube-controller-manager",
       "timeField": "timestamp"
      },
      {
       "alias": "Rss {{labels.namespace.keyword}}-{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"containerMemory-Masters\" AND labels.container.keyword: kube-controller-manager",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Kube-scheduler usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.container.keyword: kube-scheduler",
       "timeField": "timestamp"
      },
      {
       "alias": "Rss {{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.container.keyword: kube-scheduler",
       "timeField": "timestamp"
      },
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU-Masters\" AND labels.container.keyword: kube-scheduler",
       "timeField": "timestamp"
      },
      {
       "alias": "Rss {{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:329",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.namespace.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory-Masters\" AND labels.container.keyword: kube-scheduler",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Top 15 Pod distribution",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.node.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: podDistribution",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod & service latency stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average pod latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "{{field}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:80",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:78",
         "field": "podReadyLatency",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:139",
         "field": "schedulingLatency",
         "id": "3",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "$$hashKey": "object:1778",
         "field": "initializedLatency",
         "id": "4",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        { "field": "containersReadyLatency", "id": "5", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: podLatencyMeasurement",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Pod latencies summary $latencyPercentile",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$latencyPercentile {{term quantileName.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:485",
         "fake": true,
         "field": "quantileName.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "6",
         "settings": { "interval": "auto", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:340",
         "field": "$latencyPercentile",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: podLatencyQuantilesMeasurement",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Service latency: ClusterIP",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "alias": "Ready latency",
       "bucketAggs": [
        {
         "$$hashKey": "object:80",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:78",
         "field": "ready",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: svcLatencyMeasurement AND type.keyword: ClusterIP",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Service latencies summary $latencyPercentile",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: svcLatencyQuantilesMeasurement",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Pod conditions latency",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "0" }, "type": "raw_data" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: podLatencyMeasurement",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  { "title": "OVNKubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "ovnkube-master CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}-{{labels.container.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.container.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "10s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.pod.keyword: /ovnkube-control-plane.*/",
     "timeField": "timestamp"
    },
    {
     "alias": "Aggregated",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.pod.keyword: /ovnkube-control-plane.*/",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovnkube-master Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}-{{labels.container.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "labels.container.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "10s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.pod.keyword: /ovnkube-control-plane.*/ ",
     "timeField": "timestamp"
    },
    {
     "alias": "Aggregated",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "10s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.pod.keyword: /ovnkube-control-plane.*/ ",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovnkube-node pods CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "10s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\" AND labels.pod.keyword: /ovnkube-node.*/",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovnkube-node pods Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "10s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovn-controller CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "10s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/ AND labels.container.keyword: \"ovn-controller\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ovn-controller Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "10s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/ AND labels.container.keyword: \"ovn-controller\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Aggregated OVNKube-node containers CPU",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "labels.container.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "10s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Aggregated OVNKube-node containers Memory",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "labels.container.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "10s", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.namespace.keyword: \"openshift-ovn-kubernetes\"  AND labels.pod.keyword: /ovnkube-node.*/",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "etcd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "etcd 99th disk WAL fsync latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4404",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"99thEtcdDiskWalFsyncDurationSeconds\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "etcd 99th disk backend commit latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4404",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"99thEtcdDiskBackendCommitDurationSeconds\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd resource utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Rss {{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: containerMemory* AND labels.container.keyword: etcd",
     "timeField": "timestamp"
    },
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: containerCPU* AND labels.container.keyword: etcd",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd 99th network peer roundtrip time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}} to {{labels.To.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:806",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:322",
       "fake": true,
       "field": "labels.To.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:259",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:278",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: 99thEtcdRoundTripTimeSeconds",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "API and Kubeproxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Only API request P99 latency - resource scoped",
     "type": "timeseries",
     "description": "histogram_quantile(0.99, sum(irate(apiserver_request_duration_seconds_bucket{apiserver=\"kube-apiserver\", verb=~\"LIST|GET\", subresource!~\"log|exec|portforward|attach|proxy\"}[2m])) by (le, resource, verb, scope))",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:1189",
         "fake": true,
         "field": "labels.verb.keyword",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.resource.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4301",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4299",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: readOnlyAPICallsLatency AND labels.scope.keyword: resource",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Read Only API request P99 latency - namespace scoped",
     "type": "timeseries",
     "description": "histogram_quantile(0.99, sum(irate(apiserver_request_duration_seconds_bucket{apiserver=\"kube-apiserver\", verb=~\"LIST|GET\", subresource!~\"log|exec|portforward|attach|proxy\"}[2m])) by (le, resource, verb, scope))",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:1189",
         "fake": true,
         "field": "labels.verb.keyword",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4301",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4299",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: readOnlyAPICallsLatency AND labels.scope.keyword: namespace",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Read Only API request P99 latency - cluster scoped",
     "type": "timeseries",
     "description": "histogram_quantile(0.99, sum(irate(apiserver_request_duration_seconds_bucket{apiserver=\"kube-apiserver\", verb=~\"LIST|GET\", subresource!~\"log|exec|portforward|attach|proxy\"}[2m])) by (le, resource, verb, scope))",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:1189",
         "fake": true,
         "field": "labels.verb.keyword",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4301",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4299",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: readOnlyAPICallsLatency AND labels.scope.keyword: cluster",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Mutating API request P99 latency",
     "type": "timeseries",
     "description": "histogram_quantile(0.99, sum(irate(apiserver_request_duration_seconds_bucket{apiserver=\"kube-apiserver\", verb=~\"POST|PUT|DELETE|PATCH\", subresource!~\"log|exec|portforward|attach|proxy\"}[2m])) by (le, resource, verb, scope))",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:1189",
         "fake": true,
         "field": "labels.verb.keyword",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4301",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4299",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: mutatingAPICallsLatency",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "API request rate",
     "type": "timeseries",
     "description": "sum(irate(apiserver_request_total{apiserver=\"kube-apiserver\",verb!=\"WATCH\"}[2m])) by (verb,resource,code) > 0",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.verb.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.resource.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: APIRequestRate",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Kubelet & CRI-O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Kubelet process by CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:134",
         "fake": true,
         "field": "labels.node.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:61",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:59",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: kubeletCPU",
       "timeField": "timestamp"
      },
      {
       "alias": "Aggregated",
       "bucketAggs": [
        {
         "$$hashKey": "object:61",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "sum" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: kubeletCPU",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Top 5 CRI-O process by CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:134",
         "fake": true,
         "field": "labels.node.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:61",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:59",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: crioCPU",
       "timeField": "timestamp"
      },
      {
       "alias": "Aggregated",
       "bucketAggs": [
        {
         "$$hashKey": "object:61",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "sum" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: crioCPU",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Top 5 Kubelet RSS by memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.node.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: kubeletMemory",
       "timeField": "timestamp"
      },
      {
       "alias": "Aggregated",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "sum" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: kubeletMemory",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Top 5 CRI-O RSS by memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:134",
         "fake": true,
         "field": "labels.node.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:61",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:59",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: crioMemory",
       "timeField": "timestamp"
      },
      {
       "alias": "Aggregated",
       "bucketAggs": [
        {
         "$$hashKey": "object:61",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "sum" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: crioMemory",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Master: $master",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "repeat": "master",
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU usage $master",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.container.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.node.keyword: $master",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Container RSS memory $master",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.container.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.namespace.keyword: openshift-operator-lifecycle-manager",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CPU $master",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.mode.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:133",
         "fake": true,
         "field": "labels.mode.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": "_value*100",
         "meta": {},
         "settings": { "script": { "inline": "_value*100" } },
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeCPU-Masters\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Memory $master",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "Utilization",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryUtilization-Masters\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker: $worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "repeat": "worker",
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU usage $worker",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.container.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: containerCPU AND labels.node.keyword: $worker",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Container RSS memory $worker",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.container.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: containerMemory AND labels.node.keyword: $worker",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CPU $worker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.mode.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:133",
         "fake": true,
         "field": "labels.mode.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": "_value*100",
         "meta": {},
         "settings": { "script": { "inline": "_value*100" } },
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeCPU-Workers\" AND labels.instance.keyword: \"$worker\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Memory $worker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "Utilization",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryUtilization-Workers\" AND labels.instance.keyword: $worker",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Infra: $infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "repeat": "infra",
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU usage $worker",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}: {{labels.container.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:843",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU\" AND labels.node.keyword: \"$infra\" AND labels.namespace.keyword: $namespace",
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.container.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: containerCPU-Infra AND labels.node.keyword: $infra",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Container RSS memory $worker",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}: {{labels.container.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:977",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory\" AND labels.node.keyword: \"$infra\" AND labels.namespace.keyword: $namespace",
       "timeField": "timestamp"
      },
      {
       "bucketAggs": [
        {
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "labels.container.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: containerMemory-Infra AND labels.node.keyword: $infra",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CPU $infra",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.mode.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:133",
         "fake": true,
         "field": "labels.mode.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": "_value*100",
         "meta": {},
         "settings": { "script": { "inline": "_value*100" } },
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeCPU-Infra\" AND labels.instance.keyword: $infra",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Memory $infra",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "available",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryAvailable-Infra\" AND labels.instance.keyword: $infra",
       "timeField": "timestamp"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryTotal-Infra\" AND labels.instance.keyword: $infra",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Aggregated worker nodes usage (only in aggregated metrics profile)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 }
  },
  {
   "title": "Avg CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.mode.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:133",
       "fake": true,
       "field": "labels.mode.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "inlineScript": "_value*100",
       "meta": {},
       "settings": { "script": { "inline": "_value*100" } },
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeCPU-AggregatedWorkers\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Avg Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Utilization",
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: \"nodeMemoryUtilization-AggregatedWorkers\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: ontainerCPU-AggregatedWorkers",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Container memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: containerMemory-AggregatedWorkers",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}